package tools.parse;

import java.util.ArrayList;

public interface StringParseGenerable<T1, T2> {
	/**
	 * This interface is use for define object that can be generated by
	 * tools.parse.StringParser. T1 is the type of the object and T2 is type
	 * used as key for hashMap.
	 */
	public T1 generateItem(ArrayList<String> args);

	public StringParseGenerable<T1, T2> init();
	/**
	 * This method is for convert a string line into an object of T1.Each
	 * Element of args would match an attribute of T1
	 */
	public String getStringKey();

	/** This method is for having a default key "type" */
	public T2 getKey();
	/** This method is for generating a key of type T2 for the object */
}
